name: Compile AutoHotkey Scripts

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:  # Allow manual trigger

jobs:
  compile:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Get AutoHotkey version info for cache key
      id: get-versions
      shell: pwsh
      run: .\.github\scripts\get-ahk-versions.ps1
    
    - name: Cache AutoHotkey binaries
      uses: actions/cache@v4
      id: cache-ahk
      with:
        path: ${{ runner.temp }}/AutoHotkey
        key: ${{ steps.get-versions.outputs.cache-key }}
        restore-keys: |
          ahk-binaries-
    
    - name: Setup AutoHotkey Compiler
      shell: pwsh
      run: .\.github\scripts\install-ahk.ps1
    
    - name: Compile AutoHotkey scripts
      id: compile
      shell: pwsh
      continue-on-error: true
      timeout-minutes: 30
      run: .\.github\scripts\compile-scripts.ps1
    
    - name: List compiled files
      shell: pwsh
      if: always()
      run: .\.github\scripts\list-compiled-files.ps1
    
    - name: Upload compiled files
      uses: actions/upload-artifact@v4
      if: always() && hashFiles('compiled/**/*.exe') != ''
      with:
        name: ahkexe-${{ github.run_number }}-${{ steps.compile.outputs.build-timestamp }}
        path: compiled/
        retention-days: 30
    
    - name: Create release (on tags)
      if: startsWith(github.ref, 'refs/tags/') && hashFiles('compiled/**/*.exe') != ''
      uses: softprops/action-gh-release@v1
      with:
        files: compiled/**/*
        draft: false
        prerelease: false
        body: |
          ## AutoHotkey Compiled Executables
          
          This release contains compiled executables for AutoHotkey scripts in both v1 and v2 formats, with 32-bit and 64-bit versions.
          
          ### Directory Structure:
          - `x86/` - 32-bit executables (both v1 and v2) with their dependencies
          - `x64/` - 64-bit executables (both v1 and v2) with their dependencies
          
          ### File Naming:
          - Files ending with `-v1-x86.exe` are AutoHotkey v1.1 32-bit versions
          - Files ending with `-v1-x64.exe` are AutoHotkey v1.1 64-bit versions
          - Files ending with `-v2-x86.exe` are AutoHotkey v2.0 32-bit versions
          - Files ending with `-v2-x64.exe` are AutoHotkey v2.0 64-bit versions
          
          ### Dependencies:
          Scripts with external dependencies (e.g., DLL files) will have their required files automatically included in the same directory as the executable, ready to run without additional setup.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
